const SlackService = require('./services/slackService');
const MessageProcessor = require('./services/messageProcessor');
const config = require('./config');
const logger = require('./utils/logger');

/**
 * AI Slack Assistant Main Application
 * Coordinates all services and handles application lifecycle
 */
class AISlackAssistant {
  constructor() {
    this.slackService = new SlackService();
    this.messageProcessor = new MessageProcessor();
    this.isRunning = false;
    this.startTime = null;
  }

  /**
   * Initialize and start the application
   */
  async start() {
    try {
      logger.info('🚀 Starting AI Slack Assistant...');
      
      // Validate configuration
      this.validateConfiguration();

      // Initialize message processor
      logger.info('Initializing message processor...');
      await this.messageProcessor.initialize();

      // Register message handler
      this.slackService.addMessageHandler(async (messageData, slackClient) => {
        await this.messageProcessor.processMessage(messageData, slackClient);
      });

      // Start Slack service
      logger.info('Starting Slack service...');
      await this.slackService.start();

      this.isRunning = true;
      this.startTime = new Date();

      logger.info('✅ AI Slack Assistant started successfully!', {
        version: '1.0.0',
        environment: config.app.nodeEnv,
        monitored_channels: config.slack.channelsToMonitor,
        auto_response: config.slack.enableAutoResponse,
        vector_storage: this.messageProcessor.isInitialized
      });

      // Schedule daily summaries if in production
      if (config.isProduction()) {
        this.scheduleDailySummaries();
      }

      // Setup graceful shutdown
      this.setupGracefulShutdown();

    } catch (error) {
      logger.error('Failed to start AI Slack Assistant', error);
      process.exit(1);
    }
  }

  /**
   * Validate configuration before starting
   */
  validateConfiguration() {
    const requiredConfig = [
      { key: 'SLACK_BOT_TOKEN', value: config.slack.botToken },
      { key: 'SLACK_APP_TOKEN', value: config.slack.appToken },
      { key: 'SLACK_SIGNING_SECRET', value: config.slack.signingSecret },
      { key: 'OPENAI_API_KEY', value: config.openai.apiKey }
    ];

    const missing = requiredConfig.filter(item => !item.value);
    
    if (missing.length > 0) {
      logger.error('Missing required configuration:', {
        missing: missing.map(item => item.key)
      });
      logger.error('Please check your .env file and ensure all required variables are set.');
      throw new Error('Missing required configuration');
    }

    logger.info('Configuration validated successfully');
  }

  /**
   * Schedule daily summaries
   */
  scheduleDailySummaries() {
    // Simple daily summary at 9 AM
    setInterval(async () => {
      const now = new Date();
      if (now.getHours() === 9 && now.getMinutes() === 0) {
        await this.sendDailySummaries();
      }
    }, 60000); // Check every minute

    logger.info('Daily summaries scheduled for 9:00 AM');
  }

  /**
   * Send daily summaries to monitored channels
   */
  async sendDailySummaries() {
    try {
      logger.info('Generating daily summaries...');
      
      for (const channel of config.slack.channelsToMonitor) {
        const summary = await this.messageProcessor.generateDailySummary(channel);
        
        if (summary && summary.total_messages > 0) {
          const summaryText = this.formatDailySummary(summary);
          await this.slackService.sendMessage(channel, summaryText);
        }
      }

    } catch (error) {
      logger.error('Error sending daily summaries', error);
    }
  }

  /**
   * Format daily summary for Slack
   * @param {Object} summary 
   * @returns {string}
   */
  formatDailySummary(summary) {
    return `📊 **Daily Summary - ${summary.date}**\n\n` +
           `💬 **Total Messages**: ${summary.total_messages}\n` +
           `🚨 **Urgent**: ${summary.urgent}\n` +
           `❓ **Questions**: ${summary.questions}\n` +
           `📅 **Meetings**: ${summary.meetings}\n` +
           `💭 **Discussions**: ${summary.discussions}\n\n` +
           '🏆 **Top Contributors**:\n' +
           summary.top_contributors.map(c => `• <@${c.user}>: ${c.count} messages`).join('\n') +
           '\n\n_Generated by AI Slack Assistant_';
  }

  /**
   * Setup graceful shutdown handlers
   */
  setupGracefulShutdown() {
    const shutdown = async (signal) => {
      logger.info(`Received ${signal}, shutting down gracefully...`);
      await this.stop();
      process.exit(0);
    };

    process.on('SIGTERM', () => shutdown('SIGTERM'));
    process.on('SIGINT', () => shutdown('SIGINT'));
    
    // Handle uncaught exceptions
    process.on('uncaughtException', (error) => {
      logger.error('Uncaught exception', error);
      shutdown('uncaughtException');
    });

    process.on('unhandledRejection', (reason, promise) => {
      logger.error('Unhandled rejection', { reason, promise });
      shutdown('unhandledRejection');
    });
  }

  /**
   * Stop the application
   */
  async stop() {
    if (!this.isRunning) return;

    try {
      logger.info('Stopping AI Slack Assistant...');
      
      // Stop Slack service
      if (this.slackService.isConnectedToSlack()) {
        await this.slackService.stop();
      }

      // Close message processor
      await this.messageProcessor.close();

      this.isRunning = false;
      logger.info('AI Slack Assistant stopped successfully');

    } catch (error) {
      logger.error('Error during shutdown', error);
    }
  }

  /**
   * Get application status
   * @returns {Object} Status information
   */
  getStatus() {
    return {
      running: this.isRunning,
      startTime: this.startTime,
      uptime: this.startTime ? Date.now() - this.startTime.getTime() : 0,
      slackConnected: this.slackService.isConnectedToSlack(),
      vectorStorageInitialized: this.messageProcessor.isInitialized,
      config: {
        environment: config.app.nodeEnv,
        autoResponse: config.slack.enableAutoResponse,
        monitoredChannels: config.slack.channelsToMonitor
      }
    };
  }

  /**
   * Handle manual commands (for testing and administration)
   * @param {string} command 
   * @param {Object} params 
   */
  async handleCommand(command, params = {}) {
    switch (command) {
    case 'status':
      return this.getStatus();
        
    case 'summary':
      return await this.messageProcessor.generateDailySummary(params.channel);
        
    case 'stats':
      return await this.messageProcessor.vectorStorage.getStats();
        
    default:
      throw new Error(`Unknown command: ${command}`);
    }
  }
}

// Create and export the main application instance
const app = new AISlackAssistant();

// Start the application if this file is run directly
if (require.main === module) {
  app.start().catch(error => {
    logger.error('Failed to start application', error);
    process.exit(1);
  });
}

module.exports = app;